# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Peminjaman.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Minjam(object):
    def setupUi(self, Minjam):
        Minjam.setObjectName("Minjam")
        Minjam.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Minjam.sizePolicy().hasHeightForWidth())
        Minjam.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(Minjam)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 70, 671, 441))
        self.groupBox.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(150, 20, 371, 61))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(50, 100, 571, 301))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.formLayoutWidget = QtWidgets.QWidget(self.frame)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 551, 258))
        self.formLayoutWidget.setObjectName("formLayoutWidget")

        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")

        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)

        self.No_Surat = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.No_Surat.setStyleSheet("background:transparent;\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-bottom:1px solid;")
        self.No_Surat.setText("")
        self.No_Surat.setClearButtonEnabled(False)
        self.No_Surat.setObjectName("No_Surat")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.No_Surat)

        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)

        self.NIP = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.NIP.setStyleSheet("background:transparent;\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-bottom:1px solid;")
        self.NIP.setInputMethodHints(QtCore.Qt.ImhTime)
        self.NIP.setText("")
        self.NIP.setClearButtonEnabled(False)
        self.NIP.setObjectName("NIP")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.NIP)

        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)

        self.ID_Barang = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.ID_Barang.setStyleSheet("background:transparent;\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-bottom:1px solid;")
        self.ID_Barang.setText("")
        self.ID_Barang.setClearButtonEnabled(False)
        self.ID_Barang.setObjectName("ID_Barang")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ID_Barang)

        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)

        self.Tgl_Peminjaman = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.Tgl_Peminjaman.setKeyboardTracking(True)
        self.Tgl_Peminjaman.setProperty("showGroupSeparator", False)
        self.Tgl_Peminjaman.setCalendarPopup(True)
        self.Tgl_Peminjaman.setObjectName("Tgl_Peminjaman")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Tgl_Peminjaman)

        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)

        self.Tgl_Pengembalian = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.Tgl_Pengembalian.setCalendarPopup(True)
        self.Tgl_Pengembalian.setObjectName("Tgl_Pengembalian")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Tgl_Pengembalian)

        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)

        self.Pilih_Gedung = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.Pilih_Gedung.setFont(font)
        self.Pilih_Gedung.setObjectName("Pilih_Gedung")
        self.Pilih_Gedung.addItem("")
        self.Pilih_Gedung.addItem("")
        self.Pilih_Gedung.addItem("")
        self.Pilih_Gedung.addItem("")
        self.Pilih_Gedung.addItem("")
        self.Pilih_Gedung.addItem("")
        self.Pilih_Gedung.addItem("")
        self.Pilih_Gedung.addItem("")
        self.Pilih_Gedung.addItem("")
        self.Pilih_Gedung.addItem("")
        self.Pilih_Gedung.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.Pilih_Gedung)

        self.No_Ruangan = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.No_Ruangan.setStyleSheet("background:transparent;\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-bottom:1px solid;")
        self.No_Ruangan.setText("")
        self.No_Ruangan.setClearButtonEnabled(False)
        self.No_Ruangan.setObjectName("No_Ruangan")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.No_Ruangan)

        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_5)

        self.FindDirectory = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.FindDirectory.setStyleSheet("background:transparent;\n"
"color: rgb(0, 0, 0);\n"
"border:none;\n"
"border-bottom:1px solid;")
        self.FindDirectory.setObjectName("FindDirectory")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.FindDirectory)

        self.DirectoryFinderButton = QtWidgets.QToolButton(self.formLayoutWidget)
        self.DirectoryFinderButton.setObjectName("DirectoryFinderButton")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.DirectoryFinderButton)

        self.Input = QtWidgets.QPushButton(self.frame)
        self.Input.setGeometry(QtCore.QRect(470, 270, 93, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Input.sizePolicy().hasHeightForWidth())
        self.Input.setSizePolicy(sizePolicy)
        self.Input.setStyleSheet("background-color: rgb(170, 255, 127);\n"
"gridline-color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 255, 255);\n"
"selection-background-color: rgb(255, 255, 255);")
        self.Input.setAutoDefault(False)
        self.Input.setDefault(False)
        self.Input.setFlat(False)
        self.Input.setObjectName("Input")

        self.BackButton = QtWidgets.QPushButton(self.groupBox)
        self.BackButton.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setKerning(False)
        self.BackButton.setFont(font)
        self.BackButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.BackButton.setMouseTracking(False)
        self.BackButton.setAutoFillBackground(False)
        self.BackButton.setStyleSheet("color: rgb(170, 255, 255);\n"
"background-color: transparent;\n"
"")
        self.BackButton.setText("")
        self.BackButton.setObjectName("BackButton")

        self.BackIcon = QtWidgets.QLabel(self.groupBox)
        self.BackIcon.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.BackIcon.setText("")
        self.BackIcon.setPixmap(QtGui.QPixmap("icon/BackIcon.png"))
        self.BackIcon.setScaledContents(True)
        self.BackIcon.setObjectName("BackIcon")

        self.label.raise_()
        self.frame.raise_()
        self.BackIcon.raise_()
        self.BackButton.raise_()
        Minjam.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Minjam)
        self.statusbar.setObjectName("statusbar")
        Minjam.setStatusBar(self.statusbar)

        #code here
        print(self.username)
        #Dapetin alamat
        self.DirectoryFinderButton.clicked.connect(self.CariinDung)
        #Nginput
        self.Input.clicked.connect(self.Inputin)

        self.retranslateUi(Minjam)
        QtCore.QMetaObject.connectSlotsByName(Minjam)

    def retranslateUi(self, Minjam):
        _translate = QtCore.QCoreApplication.translate
        Minjam.setWindowTitle(_translate("Minjam", "Peminjaman"))
        self.label.setText(_translate("Minjam", "Form Peminjaman"))
        self.label_2.setText(_translate("Minjam", "No. Surat"))
        self.No_Surat.setPlaceholderText(_translate("Minjam", "No. Surat Peminjaman"))
        self.label_3.setText(_translate("Minjam", "NIP"))
        self.NIP.setPlaceholderText(_translate("Minjam", "NIP"))
        self.label_4.setText(_translate("Minjam", "ID_Barang"))
        self.ID_Barang.setPlaceholderText(_translate("Minjam", "ID_Barang"))
        self.label_6.setText(_translate("Minjam", "Tanggal Peminjaman"))
        self.label_7.setText(_translate("Minjam", "Tanggal Pengembalian"))
        self.label_8.setText(_translate("Minjam", "Lokasi Barang"))
        self.Pilih_Gedung.setCurrentText(_translate("Minjam", "- Pilih Gedung -"))
        self.Pilih_Gedung.setItemText(0, _translate("Minjam", "- Pilih Gedung -"))
        self.Pilih_Gedung.setItemText(1, _translate("Minjam", "A"))
        self.Pilih_Gedung.setItemText(2, _translate("Minjam", "B"))
        self.Pilih_Gedung.setItemText(3, _translate("Minjam", "C"))
        self.Pilih_Gedung.setItemText(4, _translate("Minjam", "D"))
        self.Pilih_Gedung.setItemText(5, _translate("Minjam", "E"))
        self.Pilih_Gedung.setItemText(6, _translate("Minjam", "F"))
        self.Pilih_Gedung.setItemText(7, _translate("Minjam", "GKU"))
        self.Pilih_Gedung.setItemText(8, _translate("Minjam", "Labtek1"))
        self.Pilih_Gedung.setItemText(9, _translate("Minjam", "Labtek2"))
        self.Pilih_Gedung.setItemText(10, _translate("Minjam", "Labtek3"))
        self.No_Ruangan.setPlaceholderText(_translate("Minjam", "Nomor Ruang"))
        self.label_5.setText(_translate("Minjam", "Scan BAST"))
        self.FindDirectory.setPlaceholderText(_translate("Minjam", "File Directory"))
        self.DirectoryFinderButton.setText(_translate("Minjam", "..."))
        self.Input.setText(_translate("Minjam", "Input"))

    def getMeAName(self,username):
        self.username=username

    def CariinDung(self):
        filename = QtWidgets.QFileDialog.getOpenFileName()
        self.path = filename[0]
        print(self.path)
        self.FindDirectory.setText(self.path)

    def Inputin(self):
        print("Bakal Nerima Data")
        #terima data


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Minjam = QtWidgets.QMainWindow()
    ui = Ui_Minjam()
    ui.getMeAName("Test")
    ui.setupUi(Minjam)
    Minjam.show()
    sys.exit(app.exec_())
